

CREATE TABLE vessels (
  imo INTEGER PRIMARY KEY,
  name CHARACTER VARYING NOT NULL,
  created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE port_calls (
  id SERIAL PRIMARY KEY,
  vessel_imo INTEGER NOT NULL REFERENCES vessels(imo) ON DELETE CASCADE,
  port_id CHARACTER VARYING NOT NULL,
  port_name CHARACTER VARYING NOT NULL,
  arrival TIMESTAMP WITH TIME ZONE NOT NULL,
  departure TIMESTAMP WITH TIME ZONE NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_date TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_date TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_date TIMESTAMP WITH TIME ZONE
);